import { app, BrowserWindow, session as electronSession } from 'electron'
import { writeFile, readFile, rm, stat } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { CookieCaptureEvent, CookieCaptureResult, CookieStatus } from '../shared/types'

// Cookie dang nhap 100% bang Electron (khong can Python/Playwright).
// -> chay duoc tren MOI may nguoi dung, khong cai them gi.

const LOGIN_PARTITION = 'persist:tblao-login'

export function cookiesPath(): string {
  return join(app.getPath('userData'), 'cookies.txt')
}

/** Chuyen cookie cua Electron sang dinh dang Netscape (yt-dlp doc duoc). */
function toNetscape(cookies: Electron.Cookie[]): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by Mivio', '']
  for (const c of cookies) {
    let domain = c.domain ?? ''
    if (!domain) continue
    const includeSub = c.hostOnly ? 'FALSE' : 'TRUE'
    if (!c.hostOnly && !domain.startsWith('.')) domain = '.' + domain
    const path = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    const expiry = c.session || !c.expirationDate ? 0 : Math.floor(c.expirationDate)
    // Tien to #HttpOnly_ cho cookie httpOnly (yt-dlp nhan dien)
    const domainField = c.httpOnly ? `#HttpOnly_${domain}` : domain
    lines.push([domainField, includeSub, path, secure, String(expiry), c.name, c.value].join('\t'))
  }
  return lines.join('\n') + '\n'
}

/**
 * Mo cua so dang nhap (Electron). Nguoi dung dang nhap roi DONG cua so ->
 * doc cookie tu session va ghi ra cookies.txt.
 */
export function captureCookies(
  url: string,
  onEvent: (e: CookieCaptureEvent) => void
): Promise<CookieCaptureResult> {
  return new Promise<CookieCaptureResult>((resolve) => {
    const ses = electronSession.fromPartition(LOGIN_PARTITION)
    const target = url && /^https?:\/\//i.test(url) ? url : 'https://www.google.com'

    const win = new BrowserWindow({
      width: 1000,
      height: 720,
      title: 'Dang nhap — Mivio',
      autoHideMenuBar: true,
      webPreferences: {
        partition: LOGIN_PARTITION,
        sandbox: true,
        contextIsolation: true,
        nodeIntegration: false
      }
    })

    // Cho phep popup dang nhap (OAuth Google...) mo trong cung session
    win.webContents.setWindowOpenHandler(() => ({ action: 'allow' }))

    onEvent({ phase: 'launching', message: 'Đang mở cửa sổ đăng nhập…' })

    let announced = false
    win.webContents.on('did-finish-load', () => {
      if (!announced) {
        announced = true
        onEvent({
          phase: 'ready',
          message: 'Hãy đăng nhập, rồi ĐÓNG cửa sổ này để lưu cookie.'
        })
      }
    })

    win.loadURL(target).catch(() => {
      /* mot so trang chan navigation truc tiep; van cho nguoi dung thao tac */
    })

    let settled = false
    win.on('closed', () => {
      if (settled) return
      settled = true
      void (async () => {
        try {
          const cookies = await ses.cookies.get({})
          await writeFile(cookiesPath(), toNetscape(cookies), 'utf-8')
          onEvent({ phase: 'saved', message: `Đã lưu ${cookies.length} cookie.`, count: cookies.length })
          resolve({ ok: true, count: cookies.length, path: cookiesPath(), error: null })
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err)
          onEvent({ phase: 'error', message: msg })
          resolve({ ok: false, count: 0, path: null, error: msg })
        }
      })()
    })
  })
}

export async function cookieStatus(): Promise<CookieStatus> {
  const path = cookiesPath()
  if (!existsSync(path)) return { has: false, path, count: 0 }
  try {
    const s = await stat(path)
    if (s.size === 0) return { has: false, path, count: 0 }
    const text = await readFile(path, 'utf-8')
    const count = text.split(/\r?\n/).filter((l) => l.trim() && !l.startsWith('#')).length
    return { has: count > 0, path, count }
  } catch {
    return { has: false, path, count: 0 }
  }
}

export async function clearCookies(): Promise<void> {
  await rm(cookiesPath(), { force: true })
  // Dang xuat that su: xoa cookie trong session dang nhap
  try {
    await electronSession.fromPartition(LOGIN_PARTITION).clearStorageData({ storages: ['cookies'] })
  } catch {
    /* bo qua */
  }
}
